name: Build Docker Images

on:
  push:
    branches: [ main, docker ]
    paths:
      - "docker/**"
  workflow_dispatch:

jobs:
  # Step 1: discover all Dockerfile variants
  discover:
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.set-matrix.outputs.variants }}
    steps:
      - uses: actions/checkout@v4

      - name: Discover Dockerfile variants
        id: set-matrix
        run: |
          # List all Dockerfile-* files in docker/ folder
          variants=$(ls docker/Dockerfile-* | sed 's|.*/Dockerfile-||' | jq -R -s -c 'split("\n")[:-1]')
          echo "variants=${variants}" >> $GITHUB_OUTPUT
  # Step 2: build each variant in parallel using matrix
  build:
    needs: discover
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        variant: ${{ fromJson(needs.discover.outputs.variants) }}

    steps:
      - uses: actions/checkout@v4

      # Setup Docker Buildx for multi-platform builds & caching
      - uses: docker/setup-buildx-action@v3

      # Login to GHCR
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile-${{ matrix.variant }}
          push: true
          tags: |
            ghcr.io/nanonabla/bali-inferbench:${{ matrix.variant }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max